export { setStaffClaims, suspendStaffAccount } from './auth/account-lifecycle.js';
export { withIdempotency, IdempotencyMismatchError } from './idempotency/guard.js';
export { requestUploadUrl } from './callables/request-upload-url.js';
export { verifyReport } from './callables/verify-report.js';
export { requestLookup } from './callables/request-lookup.js';
export { dispatchResponder } from './callables/dispatch-responder.js';
export { cancelDispatch } from './callables/cancel-dispatch.js';
export { rejectReport } from './callables/reject-report.js';
export { acceptDispatch } from './callables/accept-dispatch.js';
export { advanceDispatch } from './callables/advance-dispatch.js';
export { declineDispatch } from './callables/decline-dispatch.js';
export { closeReport } from './callables/close-report.js';
export { requestAgencyAssistance, acceptAgencyAssistance, declineAgencyAssistance, } from './callables/request-agency-assistance.js';
export { enterFieldMode, exitFieldMode } from './callables/enter-field-mode.js';
export { shareReport } from './callables/share-report.js';
export { addCommandChannelMessage } from './callables/add-command-channel-message.js';
export { borderAutoShareTrigger } from './triggers/border-auto-share.js';
export declare const processInboxItem: import("firebase-functions").CloudFunction<import("firebase-functions/firestore").FirestoreEvent<import("firebase-functions/firestore").QueryDocumentSnapshot | undefined, {
    inboxId: string;
}>>;
export declare const onMediaFinalize: import("firebase-functions").CloudFunction<import("firebase-functions/storage").StorageEvent>;
export { onMediaRelocate } from './triggers/on-media-relocate.js';
export { inboxReconciliationSweep } from './triggers/inbox-reconciliation-sweep.js';
export { dispatchMirrorToReport } from './triggers/dispatch-mirror-to-report.js';
export { dispatchTimeoutSweep } from './triggers/dispatch-timeout-sweep.js';
export { dispatchSmsOutbox } from './triggers/dispatch-sms-outbox.js';
export { evaluateSmsProviderHealth } from './triggers/evaluate-sms-provider-health.js';
export { reconcileSmsDeliveryStatus } from './triggers/reconcile-sms-delivery-status.js';
export { cleanupSmsMinuteWindows } from './triggers/cleanup-sms-minute-windows.js';
export { adminOperationsSweep } from './scheduled/admin-operations-sweep.js';
export { smsDeliveryReport } from './http/sms-delivery-report.js';
export { smsInboundWebhook } from './http/sms-inbound.js';
export { smsInboundProcessor } from './firestore/sms-inbound-processor.js';
//# sourceMappingURL=index.d.ts.map